schema = 1
name = "Testmod"
modid = "testmod"
version = "${version}"

mixins = "testmod.mixins.json"

[[entrypoints]]
id = "common"
path = "io.github.joemama.testmod.Testmod"

[[entrypoints]]
id = "client"
path = "io.github.joemama.testmod.TestmodClient"

