schema = 1
name = "Testmod"
modid = "testmod"
version = "${version}"

mixins = "testmod.mixins.json"

[[entrypoints]]
id = "common"
specifier = "io.github.joemama.testmod.Testmod"

[[entrypoints]]
id = "client"
specifier = "io.github.joemama.testmod.TestmodClient"

[[dependencies.requires]]
modid = "kittens"
version = "*"