schema = 1
name = "Kittens API"
version = "${version}"
description = "A modern modding API for the Felis project"
modid = "kittens"

access-widener = "kittens.accesswidener"
mixins = "kittens.mixins.json"

[[transformations]]
name = "Minecraft client entrypoint transformation"
targets = ["net.minecraft.client.Minecraft"]
specifier = "felis.kittens.core.client.MinecraftTransformation"

# Technically not needed since micromixin and access-widener both require felis but whatever.
# Make a clear dependency. We might need to overwrite it.
[[dependencies.requires]]
modid = "felis"
version = ">=1.8.1-alpha"

[[dependencies.requires]]
modid = "micromixin"
version = "*"

[[dependencies.requires]]
modid = "access-widener"
version = "*"

[[dependencies.requires]]
modid = "minecraft"
version = "1.21.*"
