schema = 1
name = "Kittens API"
version = "${version}"
description = "A modern modding API for the Felis project"
modid = "kittens"

access-widener="kittens.accesswidener"
mixins = "api.mixins.json"

[[transforms]]
name = "BuiltInRegistries transformation for common entrypoint"
path = "felis.kittens.core.BuiltInRegistriesTransformation"
target = "net.minecraft.core.registries.BuiltInRegistries"

[[transforms]]
name = "Minecraft transformation for client entrypoint"
path = "felis.kittens.core.client.MinecraftTransformation"
target = "net.minecraft.client.Minecraft"

[[transforms]]
name = "Main transformation for server entrypoint"
path = "felis.kittens.core.server.MainTransformation"
target = "net.minecraft.server.Main"

