schema = 1
name = "Kittens API"
version = "${version}"
description = "A modern modding API for the Felis project"
modid = "kittens"

access-widener = "kittens.accesswidener"
mixins = "api.mixins.json"

[[transformations]]
name = "Minecraft client entrypoint transformation"
targets = ["net.minecraft.client.Minecraft"]
specifier = "felis.kittens.core.client.MinecraftTransformation"