name = "Kittens API"
version = "${version}"
description = "A modern modding API for the Felis project"
modid = "kittens"

[[transforms]]
name = "BuiltInRegistries transformation for common entrypoint"
path = "felis.kittens.core.BuiltInRegistriesTransformation"
target = "net.minecraft.core.registries.BuiltInRegistries"

[[transforms]]
name = "Bootstrap access widener"
path = "felis.kittens.core.BootstrapTransformation"
target = "net.minecraft.server.Bootstrap"

[[transforms]]
name = "Minecraft transformation for client entrypoint"
path = "felis.kittens.core.client.MinecraftTransformation"
target = "net.minecraft.client.Minecraft"

[[transforms]]
name = "Main transformation for server entrypoint"
path = "felis.kittens.core.server.MainTransformation"
target = "net.minecraft.server.Main"

[[transforms]]
name = "Options transformation for mutable access to keyMappings field"
path = "felis.kittens.keymapping.OptionsTransformation"
target = "net.minecraft.client.Options"

[[mixins]]
path = "api.mixins.json"
